apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull
spec:
  selector:
    matchLabels:
      prepull-test-images: e2e
  template:
    metadata:
      labels:
        prepull-test-images: e2e
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      initContainers:
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/busybox:1.29
        name: busybox1
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/curl:1803
        name: curl2
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/java:openjdk-8-jre
        name: java3
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/test-webserver:1.0
        name: test-webserver4
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/cassandra:v13
        name: cassandra5
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/dnsutils:1.1
        name: dnsutils6
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/echoserver:2.2
        name: echoserver7
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/entrypoint-tester:1.0
        name: entrypoint-tester8
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/etcd:v3.3.10
        name: etcd9
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/etcd:3.3.10
        name: etcd10
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/fakegitserver:1.0
        name: fakegitserver11
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/gb-frontend:v6
        name: gb-frontend12
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/gb-redisslave:v3
        name: gb-redisslave13
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/hazelcast-kubernetes:3.8_1
        name: hazelcast-kubernetes14
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/hostexec:1.1
        name: hostexec15
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/iperf:1.0
        name: iperf16
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/jessie-dnsutils:1.0
        name: jessie-dnsutils17
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/kitten:1.0
        name: kitten18
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/liveness:1.1
        name: liveness19
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/logs-generator:1.0
        name: logs-generator20
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/mounttest:1.0
        name: mounttest21
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/nautilus:1.0
        name: nautilus22
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/net:1.0
        name: net23
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/netexec:1.1
        name: netexec24
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/nettest:1.0
        name: nettest25
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/nginx:1.14-alpine
        name: nginx26
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/nginx:1.15-alpine
        name: nginx27
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/no-snat-test:1.0
        name: no-snat-test28
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/pause:3.1
        name: pause29
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/port-forward-tester:1.0
        name: port-forward-tester30
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/porter:1.0
        name: porter31
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/redis:1.0
        name: redis32
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/resource-consumer:1.4
        name: resource-consumer33-1
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/resource-consumer:1.5
        name: resource-consumer33-2
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/resource-consumer-controller:1.0
        name: resource-consumer-controller34
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/rethinkdb:1.16.0_1
        name: rethinkdb35
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/sample-apiserver:1.10
        name: sample-apiserver36
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/serve-hostname:1.1
        name: serve-hostname37
        command: ["cmd", "exit"]
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/webhook:1.13v1
        name: webhook38
        command: ["cmd", "exit"]
      containers:
      - image: mcr.microsoft.com/k8s/core/pause:1.0.0
        name: pause
